apiVersion: 1

# list of datasources to insert/update
datasources:
  - name: PostgreSQL
    type: postgres
    access: proxy
    url: postgres.:5432
    database: grafana_db
    user: grafana_user
    secureJsonData:
      password: 'user123'
    jsonData:
      sslmode: 'disable'
